import type { Metadata } from "next";
import { Mail, MapPin } from "lucide-react";
import AgriNav from "@/components/layout/AgriNav";
import PageHero from "@/components/marketing/PageHero";
import MarketingFooter from "@/components/marketing/MarketingFooter";
import Reveal from "@/components/ui/Reveal";

export const metadata: Metadata = {
  title: "Privacy Policy — Agricoders",
  description: "How Agricoders and Logistack Plan collect, use, and protect your data.",
};

const UPDATED = "August 21, 2026";

const SECTIONS = [
  {
    title: "1. Who we are",
    body: `Agricoders ("we", "us", "our") builds and operates Logistack Plan, LivestockPro, and related agribusiness tools. Logistack Plan is operated by Logistack Ltd, based in Kigali, Rwanda. This policy covers the personal data we collect when you use our websites and applications.`,
  },
  {
    title: "2. Information we collect",
    body: `We collect information you provide directly — such as your name, email address, and company details when you create an account or submit a business plan — and information collected automatically, such as usage data, device information, and cookies needed to keep you signed in and the app working correctly. Authentication (sign-in/sign-up) is handled by our identity provider, Clerk, which processes your credentials on our behalf.`,
  },
  {
    title: "3. How we use your information",
    body: `We use your information to operate and improve our products, generate the business plans and financial models you request, communicate with you about your account, and maintain the security of our systems. We do not sell your personal data to third parties.`,
  },
  {
    title: "4. Data generated by our AI tools",
    body: `When you use Logistack Plan's AI-assisted generation features, the business details you provide are sent to our AI provider solely to generate your requested document and are not used to train third-party models beyond what is standard for that provider's API usage.`,
  },
  {
    title: "5. Data sharing",
    body: `We share data only with service providers that help us operate our platform (hosting, authentication, email delivery, AI generation) under agreements that require them to protect your data, or when required by law.`,
  },
  {
    title: "6. Data retention & your rights",
    body: `We retain your data for as long as your account is active or as needed to provide our services. You may request access to, correction of, or deletion of your personal data at any time by contacting us using the details below.`,
  },
  {
    title: "7. Security",
    body: `We use industry-standard technical and organizational measures to protect your data, including encrypted connections and access controls. No system is perfectly secure, and we encourage you to use a strong, unique password.`,
  },
  {
    title: "8. Changes to this policy",
    body: `We may update this Privacy Policy from time to time. We will post the updated version here with a revised date at the top of the page.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col bg-white dark:bg-gray-900">
      <AgriNav />

      <PageHero eyebrow="Legal" title="Privacy Policy">
        <p className="text-sm text-gray-500 dark:text-gray-400">Last updated: {UPDATED}</p>
      </PageHero>

      <section className="pb-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl">
            {SECTIONS.map((s, i) => (
              <Reveal key={s.title} delay={Math.min(i * 40, 200)} className="mb-8">
                <h2 className="mb-2.5 text-[19px] font-bold text-gray-900 dark:text-white">{s.title}</h2>
                <p className="text-[15px] leading-relaxed text-gray-600 dark:text-gray-400">{s.body}</p>
              </Reveal>
            ))}

            <Reveal delay={220}>
              <div className="mt-10 rounded-xl border border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-950 p-5">
                <h3 className="mb-3 text-[15px] font-bold text-gray-900 dark:text-white">Contact us</h3>
                <div className="mb-2 flex items-center gap-2">
                  <Mail size={14} className="flex-shrink-0 text-green-600" />
                  <a href="mailto:logistackltd@gmail.com" className="text-sm text-gray-600 dark:text-gray-400 no-underline">
                    logistackltd@gmail.com
                  </a>
                </div>
                <div className="flex items-start gap-2">
                  <MapPin size={14} className="mt-0.5 flex-shrink-0 text-green-600" />
                  <span className="text-sm text-gray-600 dark:text-gray-400">Deco Center — NYARUTARAMA, Kigali, Rwanda</span>
                </div>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      <MarketingFooter />
    </div>
  );
}
