import Link from "next/link";
import type { Metadata } from "next";
import { Sprout, Mail, MapPin } from "lucide-react";
import AgriNav from "@/components/layout/AgriNav";
import Reveal from "@/components/ui/Reveal";

export const metadata: Metadata = {
  title: "Privacy Policy — Agricoders",
  description: "How Agricoders and Logistack Plan collect, use, and protect your data.",
};

const UPDATED = "August 21, 2026";

const SECTIONS = [
  {
    title: "1. Who we are",
    body: `Agricoders ("we", "us", "our") builds and operates Logistack Plan, LivestockPro, and related agribusiness tools. Logistack Plan is operated by Logistack Ltd, based in Kigali, Rwanda. This policy covers the personal data we collect when you use our websites and applications.`,
  },
  {
    title: "2. Information we collect",
    body: `We collect information you provide directly — such as your name, email address, and company details when you create an account or submit a business plan — and information collected automatically, such as usage data, device information, and cookies needed to keep you signed in and the app working correctly. Authentication (sign-in/sign-up) is handled by our identity provider, Clerk, which processes your credentials on our behalf.`,
  },
  {
    title: "3. How we use your information",
    body: `We use your information to operate and improve our products, generate the business plans and financial models you request, communicate with you about your account, and maintain the security of our systems. We do not sell your personal data to third parties.`,
  },
  {
    title: "4. Data generated by our AI tools",
    body: `When you use Logistack Plan's AI-assisted generation features, the business details you provide are sent to our AI provider solely to generate your requested document and are not used to train third-party models beyond what is standard for that provider's API usage.`,
  },
  {
    title: "5. Data sharing",
    body: `We share data only with service providers that help us operate our platform (hosting, authentication, email delivery, AI generation) under agreements that require them to protect your data, or when required by law.`,
  },
  {
    title: "6. Data retention & your rights",
    body: `We retain your data for as long as your account is active or as needed to provide our services. You may request access to, correction of, or deletion of your personal data at any time by contacting us using the details below.`,
  },
  {
    title: "7. Security",
    body: `We use industry-standard technical and organizational measures to protect your data, including encrypted connections and access controls. No system is perfectly secure, and we encourage you to use a strong, unique password.`,
  },
  {
    title: "8. Changes to this policy",
    body: `We may update this Privacy Policy from time to time. We will post the updated version here with a revised date at the top of the page.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <AgriNav />

      <section className="py-20 text-center bg-white relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div
            className="mkt-float-slow absolute rounded-full blur-3xl"
            style={{ top: -60, left: "50%", transform: "translateX(-50%)", width: 500, height: 260, background: "rgba(46,125,50,0.06)" }}
          />
        </div>
        <div className="container position-relative">
          <div className="row justify-content-center">
            <Reveal className="col-lg-7">
              <p className="text-xs font-bold uppercase tracking-widest mb-4" style={{ color: "#2E7D32", letterSpacing: "0.14em" }}>
                Legal
              </p>
              <h1 className="font-extrabold text-gray-900 mb-3 leading-tight" style={{ fontSize: "clamp(28px, 5vw, 48px)" }}>
                Privacy Policy
              </h1>
              <p className="text-gray-500" style={{ fontSize: 14 }}>Last updated: {UPDATED}</p>
            </Reveal>
          </div>
        </div>
      </section>

      <section className="pb-24">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              {SECTIONS.map((s, i) => (
                <Reveal key={s.title} delay={Math.min(i * 40, 200)} className="mb-8">
                  <h2 className="font-bold text-gray-900 mb-2.5" style={{ fontSize: 19 }}>{s.title}</h2>
                  <p className="text-gray-600 leading-relaxed" style={{ fontSize: 15 }}>{s.body}</p>
                </Reveal>
              ))}

              <Reveal delay={220}>
                <div
                  className="rounded-xl p-5 mt-10"
                  style={{ background: "#F5F7FA", border: "1px solid #E0E0E0" }}
                >
                  <h3 className="font-bold text-gray-900 mb-3" style={{ fontSize: 15 }}>Contact us</h3>
                  <div className="d-flex align-items-center gap-2 mb-2">
                    <Mail size={14} style={{ color: "#2E7D32", flexShrink: 0 }} />
                    <a href="mailto:logistackltd@gmail.com" className="text-sm no-underline text-gray-600">
                      logistackltd@gmail.com
                    </a>
                  </div>
                  <div className="d-flex align-items-start gap-2">
                    <MapPin size={14} style={{ color: "#2E7D32", flexShrink: 0, marginTop: 2 }} />
                    <span className="text-sm text-gray-600">Deco Center — NYARUTARAMA, Kigali, Rwanda</span>
                  </div>
                </div>
              </Reveal>
            </div>
          </div>
        </div>
      </section>

      <footer className="bg-black border-t py-8" style={{ borderColor: "rgba(255,255,255,0.08)" }}>
        <div className="container">
          <div className="d-flex flex-column flex-sm-row align-items-center justify-content-between gap-3">
            <Link href="/" className="d-flex align-items-center gap-2 no-underline">
              <div style={{ width: 28, height: 28, background: "#2E7D32", borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center" }}>
                <Sprout size={13} color="white" />
              </div>
              <span className="font-bold text-white" style={{ fontSize: 14 }}>Agricoders</span>
            </Link>
            <Link href="/terms" className="no-underline" style={{ fontSize: 13, color: "#6b7280" }}>
              Terms of Service →
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
